### ISSUE TITLE
General settings in config.ini.php gets overwritten

### ISSUE THREAD

**Issue by Kiina** [MarvAmBass/docker-piwik#9]
I started the container with minimal config and got the trusted host warning.
I looked into the piwik/config/config.ini.php and it looked like this.
Seems like the enable_trusted_host_check=0 option gets overwritten or something.

```
[database]
host = "mysql"
username = "root"
password = "example"
dbname = "piwik"
tables_prefix = "piwik_"
charset = "utf8"

[General]
salt = "the random salt"
trusted_hosts[] = "localhost"

[PluginsInstalled]
Long list of all the plugins
```

**Comment by MarvAmBass** [comment]
can you give me the line you used to start the container (without passwords and personal data)

**Comment by Kiina** [comment]
Here is my docker-compose file. The VIRTUAL_HOST is just for the [ngnix reverse proxy docker](https://github.com/jwilder/nginx-proxy) that i use

```
piwik:
  image: marvambass/piwik
  links:
    - db:mysql
  restart: always
  environment:
    - PIWIK_MYSQL_USER=
    - PIWIK_MYSQL_PASSWORD=
    - VIRTUAL_HOST=
db:
  image: mariadb
  restart: always
  volumes:
    - /srv/database:/data
  environment:
    MYSQL_ROOT_PASSWORD:
```
